stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
      - data/raw
    params:
      - prepare
    outs:
      - data/processed
  tune:
    cmd: python src/tune.py
    deps:
      - src/tune.py
      - data/processed
    params:
      - tune
      - prepare.processed
    outs:
      - models
      - eval/metrics.json
      - eval/params.json
